const float SENIORCAR_WHEEL_BASE_LENGTH = 0.9;
const float SENIORCAR_HARF_TREAD_LENGTH = 0.285;

const float SENIORCAR_WHEEL_RADIUS = 0.13;
const float SENIORCAR_WHEEL_THICKNESS = 0.08;

const float SENIORCAR_COG_HEIGHT = 0.6;
const float GRVITY_ACCELERATION = 9.806;