const float SENIORCAR_WHEEL_BASE_LENGTH = 1.75;
const float SENIORCAR_HARF_TREAD_LENGTH = 0.71;

const float SENIORCAR_WHEEL_RADIUS = 0.33;
const float SENIORCAR_WHEEL_THICKNESS = 0.1;

const float SENIORCAR_COG_HEIGHT = 0.6;
const float GRVITY_ACCELERATION = 9.806;

const float SENIORCAR_FULL_LENGTH = 1.9;
const float SENIORCAR_FULL_WIDTH  = 0.8;
const float SENIORCAR_FULL_HEIGHT = 0.8;

const float SENIORCAR_DANGER_ZMP_POS_Y = SENIORCAR_HARF_TREAD_LENGTH;