const float SENIORCAR_WHEEL_BASE_LENGTH = 0.9;
const float SENIORCAR_HARF_TREAD_LENGTH = 0.285;

const float SENIORCAR_WHEEL_RADIUS = 0.13;
const float SENIORCAR_WHEEL_THICKNESS = 0.08;

const float SENIORCAR_COG_HEIGHT = 0.6;
const float GRVITY_ACCELERATION = 9.806;

const float SENIORCAR_FULL_LENGTH = 1.18;
const float SENIORCAR_FULL_WIDTH  = 0.65;
const float SENIORCAR_FULL_HEIGHT = 1.08;

const float SENIORCAR_DANGER_ZMP_POS_Y = SENIORCAR_HARF_TREAD_LENGTH;
const float SENIORCAR_TIRE_MOVABLE_LENGHT = 0.03;